apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: narmesteleder
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
spec:
  image: {{ image }}
  gcp:
    sqlInstances:
      - name: narmesteleder-db-instance
        type: POSTGRES_12
        diskSize: 10
        databases:
          - name: narmesteleder
            envVarPrefix: NAIS_DATABASE
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /is_alive
    initialDelay: 30
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /is_ready
    initialDelay: 60
    periodSeconds: 5
    timeout: 1
  prometheus:
    enabled: true
    path: /prometheus
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 400m
      memory: 768Mi
  vault:
    enabled: false
  envFrom:
    - secret: narmesteleder-secret
    - secret: narmesteleder-redis-password
    - configmap: loginservice-idporten
  ingresses:
    - "https://narmesteleder.dev.nav.no"
    - "https://narmesteleder.dev.intern.nav.no"
  webproxy: true
  kafka:
    pool: nav-dev
  azure:
    application:
      enabled: true
      tenant: trygdeetaten.no
  tokenx:
    enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: syfosoknad
          namespace: flex
          cluster: dev-fss
        - application: syfovarsel
          namespace: flex
          cluster: dev-fss
        - application: syfobrukertilgang
          namespace: default
          cluster: dev-fss
        - application: syfomoteadmin
          namespace: default
          cluster: dev-fss
        - application: syfooppfolgingsplanservice
          namespace: team-esyfo
          cluster: dev-fss
        - application: modiasyforest
          namespace: default
          cluster: dev-fss
        - application: syfosmaltinn
        - application: narmesteleder
        - application: sykmeldinger-arbeidsgiver
        - application: sykmeldinger-backend
          namespace: teamsykmelding
          cluster: dev-fss
        - application: debug-dings
          namespace: plattformsikkerhet
        - application: notifikasjon-bruker-api
          namespace: fager
          cluster: dev-fss
    outbound:
      rules:
        - application: narmesteleder-redis
  env:
    - name: SECURITYTOKENSERVICE_URL
      value: https://api-gw-q1.oera.no/security-token-service/rest/v1/sts/token
    - name: PDL_GRAPHQL_PATH
      value: https://api-gw-q1.oera.no/pdl-api/graphql
    - name: KAFKA_CLIENT_ID
      value: narmesteleder
    - name: REGISTER_BASE_PATH
      value: https://api-gw-q1.oera.no
    - name: ALLOWED_ORIGIN
      value: tjenester-q1.nav.no
